data_dir = "./data"

[tari_node]
address = "192.168.86.207"
port = 18142

[l1]
base_node_grpc = "http://192.168.86.207:18142"
wallet_grpc = "http://192.168.86.207:18143"
network = "Esmeralda"

[network]
listen_addr = "/ip4/0.0.0.0/tcp/9000"
bootstrap_peers = []
max_peers = 50

[rpc]
listen_addr = "0.0.0.0"
port = 18000
