data_dir = "./testnet_data/node1/data"

[tari_node]
address = "127.0.0.1"
port = 18142

[network]
listen_addr = "/ip4/0.0.0.0/tcp/9000"
bootstrap_peers = []
max_peers = 50

[rpc]
listen_addr = "127.0.0.1"
port = 18000
